name: run_all_tests
on: [push, pull_request, workflow_dispatch]

jobs:
  RunAllTests:
    runs-on: ubuntu-latest    
    container: python    
    steps:      
      - uses: actions/checkout@v2      
      - name: run_all_tests        
        run: |     
          conda install -c conda-forge librosa 
          pip install pytest        
          python -m pytest